sks/sks/Controllers/SmartHomeController.cs
using sks.ActionFilters;
using sks.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sks.Controllers
{
    [ErrorHandleActionFilter]
    public class SmartHomeController : BaseController
    {
        // GET: SmartHome
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Wireless()
        {
            BaseView model = new BaseView();
            model.IsMoblie = IsFromMobile();
            return View(model);
        }

        public ActionResult Care()
        {
            return View();
        }

        public ActionResult Community()
        {
            return View();
        }
    }
}

sks/sks/Views/SmartHome/Index.cshtml
@{
    string url = Request.Url.Scheme + "://" + Request.Url.Host + Request.Url.LocalPath;
    ViewBag.Title = "新保智慧家 守護您的家";
}
@section head{
    <title>新光保全-新保智慧家 守護您的家</title>
    <meta name="description" content="無線設備讓家更科技智慧，讓您更安心! 家庭、社區與居家照護陪伴，24小時監控中心，全年365天服務，免費到府諮詢規劃，新光保全智慧守護您的家。" />
    <meta name="twitter:title" content="新光保全-新保智慧家 守護您的家" />
    <meta name="twitter:description" content="無線設備讓家更科技智慧，讓您更安心! 家庭、社區與居家照護陪伴，24小時監控中心，全年365天服務，免費到府諮詢規劃，新光保全智慧守護您的家。" />
    <meta property="og:title" content="新光保全-新保智慧家 守護您的家" />
    <meta property="og:description" content="無線設備讓家更科技智慧，讓您更安心! 家庭、社區與居家照護陪伴，24小時監控中心，全年365天服務，免費到府諮詢規劃，新光保全智慧守護您的家。" />
    <link rel="canonical" href="@url" />
}

<section class="text-black h5 font-bold text-center text-lg-left">
    <div class="carousel slide carousel-fade" id="main-banner" data-ride="carousel" data-pause="false">
        <div class="carousel-inner">
            <div class="carousel-item active" data-interval="10000">
                <div class="bg-cover text-vertical-center vh-75 d-lg-none" style="background-image:url(/Content/sks/img/home-banner-sm.jpg);"></div>
                <div class="bg-cover text-vertical-center vh-75 bg-left d-none d-lg-flex" style="background-image:url(/Content/sks/img/banner-index-1.jpg);">
                    <div class="col-lg-6 offset-lg-6">
                        <svg width="300" height="100">
                            <use xlink:href="~/Content/sks/img/sprite.svg#icon-wireless-logo-03"></use>
                        </svg>
                        <h2 class="h1">Smart Home</h2>
                        <h2>守護你的家</h2>
                        <p>無線設備，讓你的家更智慧</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="mb-6 mb-lg-8">
    <div class="container-fluid text-paragraph-gray h6 text-center">
        <div class="row flex-row-reverse">
            <a class="col-md-6 offset-xl-1 px-0" href="@Url.Action("Community","SmartHome")">
                <div class="bg-cover vh-50 bg-left SKS fadeIn slow" style="background-image:url(/Content/sks/img/48222484.jpg);"></div>
            </a>
            <div class="col-md-6 col-xl-3 text-vertical-center py-4 SKS fadeIn slow delay-300ms">
                <h2>社區雲端守護</h2>
                <p>傳統的保全駐衛警已不敷管理需求</p>
                <p class="mb-4">您需要更智慧的物聯網社區安全解決方案</p>
                <a class="btn btn-outline-pill-dark self-center h5 font-bold" href="@Url.Action("Community","SmartHome")">了解更多</a>
            </div>
        </div>
        <div class="row">
            <a href="@Url.Action("Wireless","SmartHome")" class="col-md-6 bg-cover vh-50 SKS fadeIn slow" style="background-image:url(/Content/sks/img/A0-BN2-02.jpg);"></a>
            <div class="col-md-6 col-xl-3 offset-xl-1 text-vertical-center py-4 SKS fadeIn slow delay-300ms">
                <h2>保全服務</h2>
                <p> 無線保全系統，建置專屬的智慧家庭</p>
                <p class="mb-4">透過無線技術及行動APP，輕鬆轉動安全、舒適且便捷的居家生活</p>
                <a class="btn btn-outline-pill-dark self-center h5 font-bold" href="@Url.Action("Wireless","SmartHome")">了解更多</a>
            </div>
        </div>
        <div class="row flex-row-reverse">
            <a href="@Url.Action("Care","SmartHome")" class="col-md-6 offset-xl-1 bg-cover bg-top vh-50 SKS fadeIn slow" style="background-image:url(/Content/sks/img/60429850.jpg);"></a>
            <div class="col-md-6 col-xl-4 text-vertical-center py-4 SKS fadeIn slow delay-300ms">
                <h2>居家照護陪伴</h2>
                <p class="mb-4">CareU雲端居家照護，24小時全天侯守護，當長輩遇到緊急狀況時，透過安心照護主機與照護中心取得聯繫，我們會協助處理意外事件、救護車救護通報、緊急聯絡人通知、到宅查看等。</p>
                <a class="btn btn-outline-pill-dark self-center h5 font-bold" href="@Url.Action("Care","SmartHome")">了解更多</a>
            </div>
        </div>
    </div>
</section>
<section class="bg-view py-6">
    <div class="container text-white">
        <div class="row no-gutters justify-center">
            <div class="col-sm-7 col-lg-5 col-xl-4 py-8">
                <h3 class="h4 font-normal mb-4">服務優勢</h3>
                <ul class="list-unstyled h3">
                    <li class="mb-4"><span class="h2">600 餘名</span><span>保全人員</span></li>
                    <li class="mb-4"><span class="h2">350 餘名</span><span>服務工程師</span></li>
                    <li class="mb-4"><span class="h2">250 餘名</span><span>業務人員</span></li>
                    <li class="mb-4"><span class="h2">250 餘輛</span><span>機動車輛</span></li>
                </ul>
            </div>
            <div class="col-sm-5 col-lg-7 col-xl-6 text-vertical-center items-center"><img class="img-fluid SKS fadeIn slow" src="~/Content/sks/img/sksandcar.png" alt="服務優勢" /></div>
        </div>
    </div>
</section>