sks/sks/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public string MainImage { get; set; }
        public string Content { get; set; }
        public System.DateTime OnlineTime { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Creater { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Updater { get; set; }
    }
}

sks/sks/ViewModels/News/NewsIndexView.cs
using sks.Models.Cmind;
using sks.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sks.ViewModels.News
{
    public class NewsIndexView :HeaderView
    {
        public NewsIndexView()
        {
            this.Sorting = "OnlineTime";
            this.IsDescending = true;
        }

        public PageResult<NewsView> PageResult { get; set; }

        public int ID { get; set; }

        public string Title { get; set; }

        public int FiscalYear { get; set; }

        public int Type { get; set; }

        public System.DateTime OnlineTime { get; set; }

        public bool? Status { get; set; }

        public System.DateTime UpdateTime { get; set; }
    }
}

sks/sks/ViewModels/News/NewsView.cs
using sks.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sks.ViewModels.News
{
    public class NewsView : HeaderView
    {
        public int ID { get; set; }

        public string Title { get; set; }

        public int Type { get; set; }

        public string MainImage { get; set; }

        public string Content { get; set; }

        public System.DateTime OnlineTime { get; set; }

        public bool Status { get; set; }
    }
}

sks/sks/Controllers/NewsController.cs
using AutoMapper;
using sks.ActionFilters;
using sks.Models;
using sks.Models.Cmind;
using sks.Repositories;
using sks.Utility.Cmind;
using sks.ViewModels.News;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sks.Controllers
{
    [ErrorHandleActionFilter]
    public class NewsController : BaseController
    {
        private NewsRepository newsRepository = new NewsRepository();

        // GET: News
        public ActionResult Index(NewsIndexView model, int year = 0)
        {
            var query = newsRepository.List((int)NewsType.News, year);
            var data = query.AsQueryable().ToPageResult<News>(model);
            model.PageResult = Mapper.Map<PageResult<NewsView>>(data);
            return View(model);
        }

        public ActionResult Detail(int id = 0)
        {
            NewsView model = new NewsView();
            if (id != 0) {
                var query = newsRepository.GetById(id);
                model = Mapper.Map<NewsView>(query);
            }
            return View(model);
        }
    }
}

sks/sks/Views/News/Detail.cshtml
@using sks.Models;
@using sks.Utility.Cmind;

@model sks.ViewModels.News.NewsView
@{
    var link = "";
    var title = "";
    var subtitle = "";
    switch (Model.Type)
    {
        case (int)NewsType.News:
            link = "/News/Index";
            title = "新聞中心";
            break;
        case (int)NewsType.ClassRoom:
            link = "/CorporateSocial/ClassRoom";
            title = "安心教室";
            subtitle = "活動";
            break;
        case (int)NewsType.Welfare:
            link = "/CorporateSocial/WelfareFoundation";
            title = "關懷社會褔利基金會";
            subtitle = "活動";
            break;
        case (int)NewsType.CultureAndArts:
            link = "/CorporateSocial/CultureArtfoundation";
            title = "文化藝術基金會";
            subtitle = "活動";
            break;
        default:
            link = "/Shareholder/Index?list=list-columns-list&nav=list-important-list";
            title = "股東會專區";
            subtitle = "重大消息";
            break;
    }
    var textclass = Model.Type == (int)NewsType.News ? "vh-33" : "vh-50";
    ViewBag.Title = title + Model.Title;
}
@section head{
    <meta property="og:title" content="新光保全 @title @Model.Title" />
    <title>新光保全 @title | @Model.Title</title>
    @if (!String.IsNullOrEmpty(Model.Content))
    {
        string content = System.Text.RegularExpressions.Regex.Replace(Model.Content, @"\<.*?\>", String.Empty).Replace("&nbsp;", String.Empty).Trim();
        if (content.Count() > 60)
        {
            content = content.Substring(0, 60);
        }
        <meta property="og:description" content="@content">
        <meta name="description" content="@content">
    }
    <style>
        @@media(max-width:1024px) {
            .vh-50 {
                height: 39vh !important;
            }
        }
    </style>
}

<section class="text-white text-center font-bold">
    <div class="carousel slide carousel-fade" id="main-banner" data-ride="carousel" data-pause="false">
        <div class="carousel-inner">
            <div class="carousel-item active" data-interval="10000">
                <div class="bg-cover text-vertical-center @textclass relative" style="background-image:url(/Content/sks/img/about-banner.jpg);">
                    <div class="mask-dark py-9">
                        <h2 class="h1">@title</h2>
                        <h2 class="h1">@subtitle</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<main class="py-6 py-lg-8">
    <div class="container py-6 py-lg-8">
        <article class="h5">
            @if (!string.IsNullOrEmpty(Model.MainImage))
            {
                <img class="img-fluid mb-4" src="https://wwwadmin.sks.com.tw/FileUploads/NewsPhoto/@Model.MainImage" />
            }
            <h2 class="h3 mb-4">@Model.Title</h2>
            <p class="text-gray mb-4">
                發布日期：
                <time>@Model.OnlineTime.ToString("yyyy-MM-dd")</time>
            </p>

            @HtmlHelperExtensions.AntiXssRaw(Model.Content)
        </article>
    </div>
    <div class="container py-6 py-lg-8"><a href="@link">< &nbsp; 返回列表</a></div>
</main>

sks/sks/Views/News/Index.cshtml
@model sks.ViewModels.News.NewsIndexView
@{
    string url = Request.Url.Scheme + "://" + Request.Url.Host + Request.Url.LocalPath;
}
@section head{
    @if (Model.PageResult.Data.Count() > 0)
    {
        var firstData = Model.PageResult.Data.FirstOrDefault();
        string content = System.Text.RegularExpressions.Regex.Replace(firstData.Content, @"\<.*?\>", String.Empty).Replace("&nbsp;", String.Empty).Trim();
        if (content.Count() > 60)
        {
            content = content.Substring(0, 60);
        }
        <meta property="og:title" content="新光保全 新聞中心 @firstData.Title" />
        <title>新光保全 新聞中心 | @firstData.Title</title>
        <meta property="og:description" content="@content">
        <meta name="description" content="@content">
        <link rel="canonical" href="@url" />
        ViewBag.Title= "新聞中心"+ firstData.Title;
    }
}

<section class="text-white text-center font-bold" id="page-top">
    <div class="carousel slide carousel-fade" id="main-banner" data-ride="carousel" data-pause="false">
        <div class="carousel-inner">
            <div class="carousel-item active" data-interval="10000">
                <div class="bg-cover text-vertical-center vh-33 relative" style="background-image:url(/Content/sks/img/about-banner.jpg);">
                    <div class="mask-dark">
                        <h2 class="h1 lineheight-vh-33">關於新保</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container-fluid full-fluid border-bottom-light-gray">
    <div class="row">
        <div class="d-none d-lg-block col-lg-3 col-xl-2 bg-aside py-6 py-lg-8">
            <aside class="list-group h5 text-center" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action" href="/About/Index#list-intro">新保簡介</a>
                @*<a class="list-group-item list-group-item-action" href="/About/Index#list-milestone">里程碑</a>*@
                <a class="list-group-item list-group-item-action" href="/About/Index#list-award">獲獎紀錄</a>
                <a class="list-group-item list-group-item-action active" href="#" aria-controls="news" role="tab" data-toggle="list">新聞中心</a>
                <a class="list-group-item list-group-item-action" href="/Robots">機器人專區</a>
                <a class="list-group-item list-group-item-action" href="/About/Index#list-groups">事業群</a>
                <a class="list-group-item list-group-item-action" href="/About/Index#list-cooperations">關係企業</a>
            </aside>
        </div>
        <div class="col-lg-9 col-xl-10 py-6 py-xl-8">
            <div class="tab-content">
                <section class="tab-pane fade show active" id="list-news" role="tabpanel" aria-labelledby="list-news-list">
                    <div class="container h6">
                        <h2 class="text-gray-57 text-center mb-4">新聞中心</h2>
                        <select class="form-control mb-4 bg-white border-black rounded" id="select-news-year">
                            <option value="0">依年分搜尋</option>
                            @for (int i = DateTime.Now.Year; i >= 2015; i--)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                        <ul class="list-unstyled divider-h mb-4">
                            @foreach (var item in Model.PageResult.Data)
                            {
                                <li class="py-4 px-lg-10 px-xl-11">
                                    <a href="@Url.Action("Detail","News",new { id = item.ID })">
                                        <time class="mr-4">@item.OnlineTime.ToString("yyyy-MM-dd")</time>
                                        <span class="d-block d-lg-inline">@item.Title</span>
                                    </a>
                                </li>
                            }
                        </ul>
                        @{
                            Html.RenderPartial("_Page", Model.PageResult);
                        }
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
    <script>
        $(function () {
            const urlParams = new URLSearchParams(window.location.search);
            const searchstr = urlParams.get('year');
            if (searchstr !== null) {
                $('#select-news-year').val(searchstr);
            }
        });
        $('#select-news-year').on('change', function (e) {
            var selectedTable = $(this).val();
            if (selectedTable) {
                toSearchResult(selectedTable);
            }
        });

        //新聞頁
        const Url = '@Url.Action("Index")';

        function toSearchResult(year) {
            var params = {
                year: year
            };
            var queryString = Object.keys(params).map(function (key) {
                return key + '=' + params[key]
            }).join('&');
            const origin = window.location.origin;
            const pathname = window.location.pathname;
            const url = origin + Url + '?' + queryString;
            window.location.href = url;
        }
    </script>
}